name: Check Markdown links

on:
    pull_request: ~
    workflow_dispatch: ~
    workflow_call: ~

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            -   uses: tcort/github-action-markdown-link-check@v1
                with: 
                    folder-path: 'docs'
